
services:
  crispget_tool:
    ports:
      - 8913:8080
    volumes:
      - type: bind
        source: $HOME/crispget_sequence_files
        target: /home/crispget_sequence_files
      - type: bind
        source: crispget_local.conf
        target: /home/CRISPGET/crispget_local.conf
    tty: true
    container_name: crispget_tool
    image: breedbase/crispget:v0.05
